"""Tests for the Phase 4A runnable vertical slice."""

from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path

from claim_audit_lab.auditor import audit_document
from claim_audit_lab.loader import load_draft, load_evidence_bundle
from claim_audit_lab.models import AuditConfig, AuditReport, EvidenceBundle
from claim_audit_lab.report import render_json_report, render_markdown_report

PROJECT_ROOT = Path(__file__).resolve().parents[1]
EXAMPLES_ROOT = PROJECT_ROOT / "examples"
SLICE_MARKDOWN = EXAMPLES_ROOT / "reports" / "ai-research-note.slice.md"
PHASE_4A_HEADER = (
    "Generated by Phase 4A vertical slice - rule checks deferred; support labels provisional."
)
FORBIDDEN_CAPABILITY_PATTERNS = (
    r"\bfact checked\b",
    r"\bverified\b",
    r"\bproven\b",
    r"\btrue\b",
    r"\bfalse\b",
)


def _ai_research_report(config: AuditConfig | None = None) -> AuditReport:
    draft = load_draft(EXAMPLES_ROOT / "drafts" / "ai-research-note.md")
    evidence_bundle = load_evidence_bundle(EXAMPLES_ROOT / "evidence" / "ai-research-evidence.yml")
    return audit_document(draft, evidence_bundle, config)


def _assert_no_forbidden_capability_language(text: str) -> None:
    lowered = text.lower()
    for pattern in FORBIDDEN_CAPABILITY_PATTERNS:
        assert re.search(pattern, lowered) is None


def test_audit_document_returns_phase_4a_report_without_support_semantics() -> None:
    """The vertical slice wires the pipeline without assigning final support labels."""
    report = _ai_research_report()

    assert report.document_id == "ai-research-note"
    assert report.summary.total_claims == 4
    assert report.summary.needs_source_claims == 2
    assert report.summary.not_audit_ready_claims == 2
    assert report.rule_flags == []
    assert {assessment.support_label for assessment in report.claims} <= {
        "needs_source",
        "not_audit_ready",
    }
    assert {
        "supported",
        "partially_supported",
        "overstated",
        "unsupported",
    }.isdisjoint({assessment.support_label for assessment in report.claims})
    assert any(assessment.candidate_evidence for assessment in report.claims)
    assert all("Phase 5" in " ".join(assessment.limitations) for assessment in report.claims)


def test_audit_document_threads_config_into_candidate_matching() -> None:
    """AuditConfig controls candidate inclusion and capping in the slice."""
    report = _ai_research_report(AuditConfig(min_overlap_score=0.95, max_candidate_evidence=1))

    candidate_counts = {
        assessment.claim.text: len(assessment.candidate_evidence) for assessment in report.claims
    }

    assert candidate_counts["The test set included 52 workflow outputs."] == 1
    assert (
        candidate_counts[
            "Unsupported claims fell from 18 outputs to 11 outputs after the provenance "
            "checklist was added."
        ]
        == 0
    )


def test_empty_evidence_bundle_returns_useful_report() -> None:
    """Empty evidence bundles produce audit output rather than a runtime failure."""
    draft = load_draft(EXAMPLES_ROOT / "drafts" / "ai-research-note.md")
    report = audit_document(draft, EvidenceBundle(sources=[]))

    assert report.summary.total_claims == 4
    assert report.summary.needs_source_claims == 4
    assert report.summary.not_audit_ready_claims == 0
    assert report.evidence_bundle_warnings
    assert all(assessment.support_label == "needs_source" for assessment in report.claims)


def test_markdown_report_contains_required_phase_4a_sections() -> None:
    """Markdown output exposes the runnable slice without overclaiming support."""
    markdown = render_markdown_report(_ai_research_report())

    assert PHASE_4A_HEADER in markdown
    assert "## Summary" in markdown
    assert "## Claim register" in markdown
    assert "## Candidate evidence" in markdown
    assert "## Limitations" in markdown
    assert "score `" in markdown
    assert "None" not in markdown
    assert re.search(r"\bnan\b", markdown.lower()) is None
    _assert_no_forbidden_capability_language(markdown)


def test_json_report_round_trips_to_audit_report() -> None:
    """JSON output remains tied to the typed report contract."""
    rendered = render_json_report(_ai_research_report())
    parsed = AuditReport.model_validate(json.loads(rendered))

    assert parsed.summary.total_claims == 4
    assert parsed.claims[0].claim.id.startswith("claim-")


def test_demo_script_writes_reports_to_requested_paths(tmp_path: Path) -> None:
    """The reviewer demo can run without dirtying checked-in report fixtures."""
    markdown_out = tmp_path / "slice.md"
    json_out = tmp_path / "slice.json"

    result = subprocess.run(
        [
            sys.executable,
            str(PROJECT_ROOT / "scripts" / "run_demo.py"),
            "--out",
            str(markdown_out),
            "--json-out",
            str(json_out),
        ],
        cwd=PROJECT_ROOT,
        check=True,
        capture_output=True,
        text=True,
    )

    assert "Wrote Markdown report" in result.stdout
    assert markdown_out.exists()
    assert json_out.exists()
    assert PHASE_4A_HEADER in markdown_out.read_text(encoding="utf-8")
    AuditReport.model_validate(json.loads(json_out.read_text(encoding="utf-8")))


def test_checked_in_slice_report_avoids_forbidden_capability_language() -> None:
    """The committed reviewer-facing slice report is gated too."""
    assert SLICE_MARKDOWN.exists()
    text = SLICE_MARKDOWN.read_text(encoding="utf-8")

    assert PHASE_4A_HEADER in text
    _assert_no_forbidden_capability_language(text)
