"""Tests for Phase 7 report rendering hardening."""

from __future__ import annotations

import json
import re
from pathlib import Path

from claim_audit_lab.auditor import audit_document
from claim_audit_lab.loader import load_draft, load_evidence_bundle
from claim_audit_lab.models import (
    AuditReport,
    AuditSummary,
    Claim,
    ClaimAssessment,
    EvidenceCandidate,
    RuleFlag,
)
from claim_audit_lab.report import render_json_report, render_markdown_report

PROJECT_ROOT = Path(__file__).resolve().parents[1]
EXAMPLES_ROOT = PROJECT_ROOT / "examples"
SLICE_MARKDOWN = EXAMPLES_ROOT / "reports" / "ai-research-note.slice.md"
SLICE_JSON = EXAMPLES_ROOT / "reports" / "ai-research-note.slice.json"
REPORT_HEADER = (
    "Generated by Claim Audit Lab - deterministic rule checks, Phase 6 audit "
    "orchestration, and Phase 7 report rendering enabled; CLI workflow remains planned."
)
FORBIDDEN_CAPABILITY_PATTERNS = (
    r"\bfact checked\b",
    r"\bverified\b",
    r"\bproven\b",
    r"\btrue\b",
    r"\bfalse\b",
)


def _ai_research_report() -> AuditReport:
    draft = load_draft(EXAMPLES_ROOT / "drafts" / "ai-research-note.md")
    evidence_bundle = load_evidence_bundle(EXAMPLES_ROOT / "evidence" / "ai-research-evidence.yml")
    return audit_document(draft, evidence_bundle)


def _ai_research_markdown() -> str:
    return render_markdown_report(_ai_research_report())


def _assert_no_forbidden_capability_language(text: str) -> None:
    lowered = text.lower()
    for pattern in FORBIDDEN_CAPABILITY_PATTERNS:
        assert re.search(pattern, lowered) is None


def test_markdown_report_contains_phase_7_human_review_sections() -> None:
    """Markdown output exposes the report surfaces required for human review."""
    markdown = _ai_research_markdown()

    assert REPORT_HEADER in markdown
    for heading in (
        "## Metadata",
        "## Executive summary",
        "## Limitations",
        "## Claim register",
        "## Claim details",
        "## Evidence links",
        "## Suggested rewrite guidance",
    ):
        assert heading in markdown
    assert (
        "| Claim ID | Claim text | Type | Support | Risk | Strongest evidence | Main issue |"
        in markdown
    )
    assert "| Source | Excerpt | Ranking score | Reliability | Date | URL | Rationale |" in markdown
    assert "| Source | Excerpt | Referenced by claims | Best ranking score |" in markdown


def test_markdown_report_surfaces_labels_flags_and_rewrite_guidance() -> None:
    """Support labels, rule flags, evidence links, and guidance are visible together."""
    markdown = _ai_research_markdown()

    assert "4 claims extracted. Findings: 1 supported, 1 partially supported" in markdown
    assert "Support: `overstated`" in markdown
    assert "Support: `supported`" in markdown
    assert "`overconfident_wording`" in markdown
    assert "`scope_overreach`" in markdown
    assert "`causal_overreach`" in markdown
    assert "`future_certainty`" in markdown
    assert "`source-001` | `excerpt-001`" in markdown
    assert (
        "`source-001` | `excerpt-001` | `claim-61e15c02b15c`, `claim-1e17db4b2188` | 0.7242"
        in markdown
    )
    assert "No candidate evidence linked from the supplied bundle." in markdown
    assert "Replace absolute wording with bounded supplied-evidence language." in markdown
    assert "Narrow the scope to the observed source, fixture, sample, or setting." in markdown
    assert (
        "Use weaker causal wording unless the supplied evidence directly supports causality."
        in markdown
    )


def test_markdown_report_preserves_support_boundary_and_quality_gate() -> None:
    """Generated prose avoids overclaiming and placeholder artifacts."""
    markdown = _ai_research_markdown()

    assert (
        "- Audit boundary: supplied-evidence support only; no outside-world assessment." in markdown
    )
    assert "- External source lookup: not used." in markdown
    assert "Candidate ranking scores inspect deterministic matching only" in markdown
    assert "Support score:" not in markdown
    assert "None" not in markdown
    assert re.search(r"\bnan\b", markdown.lower()) is None
    assert "Phase 5 rule-assessment slice" not in markdown
    assert "Initial Phase 5 rules" not in markdown
    _assert_no_forbidden_capability_language(markdown)


def test_json_report_round_trips_to_audit_report_without_null_values() -> None:
    """JSON output remains tied to the typed report contract."""
    rendered = render_json_report(_ai_research_report())
    parsed = AuditReport.model_validate(json.loads(rendered))

    assert '"document_id": "ai-research-note"' in rendered
    assert "null" not in rendered
    assert parsed.summary.total_claims == 4
    assert parsed.claims[0].claim.id.startswith("claim-")


def test_checked_in_slice_fixtures_match_current_renderer_output() -> None:
    """The committed AI research slice stays synchronized with renderer output."""
    report = _ai_research_report()

    assert SLICE_MARKDOWN.read_text(encoding="utf-8") == render_markdown_report(report)
    assert SLICE_JSON.read_text(encoding="utf-8") == render_json_report(report)


def test_markdown_report_handles_empty_warning_report_without_empty_sections() -> None:
    """A zero-claim report still renders useful sections and warnings."""
    report = AuditReport(
        document_id="empty-note",
        summary=AuditSummary(total_claims=0),
        evidence_bundle_warnings=["No evidence sources were supplied."],
        limitations=["Supplied evidence only."],
    )
    markdown = render_markdown_report(report)

    assert "## Evidence bundle warnings" in markdown
    assert "No claims were extracted from the draft." in markdown
    assert "No candidate evidence links were found." in markdown
    assert "No rewrite guidance was generated for this report." in markdown
    _assert_no_forbidden_capability_language(markdown)


def test_markdown_report_handles_optional_candidate_and_explanation_fields() -> None:
    """Missing optional candidate fields render as reviewer-friendly text."""
    claim = Claim(id="claim-manual-001", text="The tool reduces review time.", claim_type="causal")
    report = AuditReport(
        document_id="manual-note",
        summary=AuditSummary(total_claims=1, supported_claims=1),
        claims=[
            ClaimAssessment(
                claim=claim,
                support_label="supported",
                risk_label="low",
                candidate_evidence=[
                    EvidenceCandidate(
                        source_id="source-manual",
                        excerpt_id="excerpt-manual",
                        score=0.42,
                    )
                ],
            )
        ],
    )
    markdown = render_markdown_report(report)

    assert "No additional explanation recorded." in markdown
    assert "No rule issue recorded." in markdown
    assert "not dated" in markdown
    assert "not supplied" in markdown
    assert "No rationale recorded." in markdown


def test_markdown_report_renders_explicit_and_fallback_rewrite_guidance() -> None:
    """Renderer guidance covers stored rewrites, rule codes, and label fallbacks."""
    rule_flags = [
        RuleFlag(
            id="flag-numeric",
            claim_id="claim-flags",
            code="numeric_mismatch",
            message="The number does not match supplied evidence.",
            risk="high",
        ),
        RuleFlag(
            id="flag-comparison",
            claim_id="claim-flags",
            code="comparison_missing",
            message="Comparison evidence is missing.",
            risk="medium",
        ),
        RuleFlag(
            id="flag-credential",
            claim_id="claim-flags",
            code="credential_missing_source",
            message="Credential source is missing.",
            risk="medium",
        ),
        RuleFlag(
            id="flag-link",
            claim_id="claim-flags",
            code="public_link_missing_source",
            message="Public link source metadata is missing.",
            risk="medium",
        ),
        RuleFlag(
            id="flag-reliability",
            claim_id="claim-flags",
            code="low_reliability_only",
            message="Direct support has weak reliability.",
            risk="medium",
        ),
        RuleFlag(
            id="flag-stale",
            claim_id="claim-flags",
            code="stale_source",
            message="Direct support is stale.",
            risk="medium",
        ),
        RuleFlag(
            id="flag-date",
            claim_id="claim-flags",
            code="date_missing_support",
            message="Date support is missing.",
            risk="medium",
        ),
    ]
    assessments = [
        ClaimAssessment(
            claim=Claim(id="claim-flags", text="The metric was 99 by 2025.", claim_type="numeric"),
            support_label="unsupported",
            risk_label="high",
            rule_flags=rule_flags,
            suggested_rewrite="Use the supported metric only.",
        ),
        ClaimAssessment(
            claim=Claim(id="claim-needed", text="The result needs a source.", claim_type="scope"),
            support_label="needs_source",
            risk_label="medium",
        ),
        ClaimAssessment(
            claim=Claim(
                id="claim-over", text="The result eliminates all risk.", claim_type="scope"
            ),
            support_label="overstated",
            risk_label="high",
        ),
        ClaimAssessment(
            claim=Claim(
                id="claim-partial", text="The result improved outcomes.", claim_type="causal"
            ),
            support_label="partially_supported",
            risk_label="medium",
        ),
        ClaimAssessment(
            claim=Claim(
                id="claim-not-ready",
                text="Background note without enough audit structure.",
                claim_type="interpretive",
            ),
            support_label="not_audit_ready",
            risk_label="medium",
        ),
    ]
    report = AuditReport(
        document_id="rewrite-note",
        summary=AuditSummary(
            total_claims=5,
            partially_supported_claims=1,
            unsupported_claims=1,
            overstated_claims=1,
            needs_source_claims=1,
            not_audit_ready_claims=1,
            high_risk_claims=2,
        ),
        claims=assessments,
        rule_flags=rule_flags,
    )
    markdown = render_markdown_report(report)

    assert "Suggested rewrite: Use the supported metric only." in markdown
    assert "Correct the number or supply evidence with the matching value." in markdown
    assert "Name the comparison evidence or soften the comparative claim." in markdown
    assert "Add a supplied credential source before keeping this credential claim." in markdown
    assert "Add supplied URL metadata before keeping this public-link claim." in markdown
    assert "Caveat the claim because direct support comes from weak source reliability." in markdown
    assert "Use newer supplied evidence or add a freshness caveat." in markdown
    assert "Add matching date evidence or remove the unsupported date detail." in markdown
    assert "Add a supplied source before presenting this claim." in markdown
    assert "Narrow the claim until it matches the supplied evidence." in markdown
    assert "Keep the supported part and caveat the unsupported part." in markdown
    assert "Support: `not_audit_ready`" in markdown
