"""Tests for the reviewer-facing report demo."""

from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path

from claim_audit_lab.auditor import audit_document
from claim_audit_lab.loader import load_draft, load_evidence_bundle
from claim_audit_lab.models import AuditReport
from claim_audit_lab.report import render_json_report, render_markdown_report

PROJECT_ROOT = Path(__file__).resolve().parents[1]
EXAMPLES_ROOT = PROJECT_ROOT / "examples"
SLICE_MARKDOWN = EXAMPLES_ROOT / "reports" / "ai-research-note.slice.md"
REPORT_HEADER = (
    "Generated by Claim Audit Lab - deterministic rule checks, Phase 6 audit "
    "orchestration, and Phase 7 report rendering enabled; Phase 8 CLI workflow is available."
)
FORBIDDEN_CAPABILITY_PATTERNS = (
    r"\bfact checked\b",
    r"\bverified\b",
    r"\bproven\b",
    r"\btrue\b",
    r"\bfalse\b",
)


def _ai_research_report() -> AuditReport:
    draft = load_draft(EXAMPLES_ROOT / "drafts" / "ai-research-note.md")
    evidence_bundle = load_evidence_bundle(EXAMPLES_ROOT / "evidence" / "ai-research-evidence.yml")
    return audit_document(draft, evidence_bundle)


def _assert_no_forbidden_capability_language(text: str) -> None:
    lowered = text.lower()
    for pattern in FORBIDDEN_CAPABILITY_PATTERNS:
        assert re.search(pattern, lowered) is None


def test_markdown_report_contains_reviewer_facing_sections() -> None:
    """Markdown output exposes rule-assessed labels without overclaiming support."""
    markdown = render_markdown_report(_ai_research_report())

    assert REPORT_HEADER in markdown
    assert "## Executive summary" in markdown
    assert "## Claim register" in markdown
    assert "## Claim details" in markdown
    assert "## Evidence links" in markdown
    assert "## Suggested rewrite guidance" in markdown
    assert "## Limitations" in markdown
    assert "Support: `" in markdown
    assert "**Rule flags**" in markdown
    assert "Ranking score" in markdown
    assert "Phase 4A label" not in markdown
    assert "Phase 5 rule-assessment slice" not in markdown
    assert "None" not in markdown
    assert re.search(r"\bnan\b", markdown.lower()) is None
    _assert_no_forbidden_capability_language(markdown)


def test_json_report_round_trips_to_audit_report() -> None:
    """JSON output remains tied to the typed report contract."""
    rendered = render_json_report(_ai_research_report())
    parsed = AuditReport.model_validate(json.loads(rendered))

    assert parsed.summary.total_claims == 4
    assert parsed.claims[0].claim.id.startswith("claim-")


def test_demo_script_writes_reports_to_requested_paths(tmp_path: Path) -> None:
    """The reviewer demo can run without dirtying checked-in report fixtures."""
    markdown_out = tmp_path / "slice.md"
    json_out = tmp_path / "slice.json"

    result = subprocess.run(
        [
            sys.executable,
            str(PROJECT_ROOT / "scripts" / "run_demo.py"),
            "--out",
            str(markdown_out),
            "--json-out",
            str(json_out),
        ],
        cwd=PROJECT_ROOT,
        check=True,
        capture_output=True,
        text=True,
    )

    assert "Wrote Markdown report" in result.stdout
    assert markdown_out.exists()
    assert json_out.exists()
    assert REPORT_HEADER in markdown_out.read_text(encoding="utf-8")
    AuditReport.model_validate(json.loads(json_out.read_text(encoding="utf-8")))


def test_checked_in_slice_report_avoids_forbidden_capability_language() -> None:
    """The committed reviewer-facing slice report is gated too."""
    assert SLICE_MARKDOWN.exists()
    text = SLICE_MARKDOWN.read_text(encoding="utf-8")

    assert REPORT_HEADER in text
    _assert_no_forbidden_capability_language(text)
