"""Tests for Phase 7 report rendering hardening."""

from __future__ import annotations

import json
import re
from datetime import date as Date
from pathlib import Path

import pytest

from claim_audit_lab.auditor import audit_document
from claim_audit_lab.loader import load_draft, load_evidence_bundle
from claim_audit_lab.models import (
    AuditReport,
    AuditSummary,
    Claim,
    ClaimAssessment,
    EvidenceCandidate,
    RuleFlag,
)
from claim_audit_lab.report import render_json_report, render_markdown_report

PROJECT_ROOT = Path(__file__).resolve().parents[1]
EXAMPLES_ROOT = PROJECT_ROOT / "examples"
SLICE_MARKDOWN = EXAMPLES_ROOT / "reports" / "ai-research-note.slice.md"
SLICE_JSON = EXAMPLES_ROOT / "reports" / "ai-research-note.slice.json"
REPORT_FIXTURES = (
    (
        "ai-research-note",
        EXAMPLES_ROOT / "drafts" / "ai-research-note.md",
        EXAMPLES_ROOT / "evidence" / "ai-research-evidence.yml",
        SLICE_MARKDOWN,
        SLICE_JSON,
    ),
    (
        "product-readme-note",
        EXAMPLES_ROOT / "drafts" / "product-readme-note.md",
        EXAMPLES_ROOT / "evidence" / "product-readme-evidence.yml",
        EXAMPLES_ROOT / "reports" / "product-readme-note.slice.md",
        EXAMPLES_ROOT / "reports" / "product-readme-note.slice.json",
    ),
)
REPORT_HEADER = (
    "Generated by Claim Audit Lab - deterministic rule checks, Phase 6 audit "
    "orchestration, and Phase 7 report rendering enabled; Phase 8 CLI workflow is available."
)
FORBIDDEN_CAPABILITY_PATTERNS = (
    r"\bfact checked\b",
    r"\bverified\b",
    r"\bproven\b",
    r"\btrue\b",
    r"\bfalse\b",
)
PUBLIC_EXAMPLE_DIRS = (
    EXAMPLES_ROOT / "drafts",
    EXAMPLES_ROOT / "evidence",
    EXAMPLES_ROOT / "reports",
)
PUBLIC_DATA_SENSITIVE_PATTERNS = (
    r"/Users/",
    r"\bCameron\s+Sanderson\b",
    r"\bQuantum\s+Allergy\b",
    r"\bOpenAI\s+Safety\s+Fellowship\b",
    r"\bAnthropic\s+Fellows\b",
    r"\bAstra\s+Fellowship\b",
    r"\bSentrex\b",
    r"\bResume\.docx\b",
    r"\bLinkedIn\b",
    r"\bConstellation\b",
    r"\bapi[_-]?key\b",
    r"\bsecret\b",
    r"\btoken\b",
    r"\bsk-[A-Za-z0-9_-]{12,}\b",
    r"\bghp_[A-Za-z0-9_]{12,}\b",
    r"\bxox[baprs]-[A-Za-z0-9-]{12,}\b",
)


def _ai_research_report() -> AuditReport:
    draft = load_draft(EXAMPLES_ROOT / "drafts" / "ai-research-note.md")
    evidence_bundle = load_evidence_bundle(EXAMPLES_ROOT / "evidence" / "ai-research-evidence.yml")
    return audit_document(draft, evidence_bundle)


def _audit_report(draft_path: Path, evidence_path: Path) -> AuditReport:
    draft = load_draft(draft_path)
    evidence_bundle = load_evidence_bundle(evidence_path)
    return audit_document(draft, evidence_bundle)


def _ai_research_markdown() -> str:
    return render_markdown_report(_ai_research_report())


def _assert_no_forbidden_capability_language(text: str) -> None:
    lowered = text.lower()
    for pattern in FORBIDDEN_CAPABILITY_PATTERNS:
        assert re.search(pattern, lowered) is None


def test_markdown_report_contains_phase_7_human_review_sections() -> None:
    """Markdown output exposes the report surfaces required for human review."""
    markdown = _ai_research_markdown()

    assert REPORT_HEADER in markdown
    for heading in (
        "## Metadata",
        "## Executive summary",
        "## Limitations",
        "## Claim register",
        "## Claim details",
        "## Evidence links",
        "## Suggested rewrite guidance",
    ):
        assert heading in markdown
    assert (
        "| Claim ID | Claim text | Type | Support | Risk | Strongest evidence | Main issue |"
        in markdown
    )
    assert "| Source | Excerpt | Ranking score | Reliability | Date | URL | Rationale |" in markdown
    assert "| Source | Excerpt | Referenced by claims | Best ranking score |" in markdown


def test_markdown_report_surfaces_labels_flags_and_rewrite_guidance() -> None:
    """Support labels, rule flags, evidence links, and guidance are visible together."""
    markdown = _ai_research_markdown()

    assert "4 claims extracted. Findings: 1 supported, 1 partially supported" in markdown
    assert "Support: `overstated`" in markdown
    assert "Support: `supported`" in markdown
    assert "`overconfident_wording`" in markdown
    assert "`scope_overreach`" in markdown
    assert "`causal_overreach`" in markdown
    assert "`future_certainty`" in markdown
    assert "`source-001` | `excerpt-001`" in markdown
    assert '<a id="evidence-source-001-excerpt-001"></a> `source-001` | `excerpt-001`' in markdown
    assert "`claim-61e15c02b15c`, `claim-1e17db4b2188` | 0.7242" in markdown
    assert "No candidate evidence linked from the supplied bundle." in markdown
    assert "Replace absolute wording with bounded supplied-evidence language." in markdown
    assert "Narrow the scope to the observed source, fixture, sample, or setting." in markdown
    assert (
        "Use weaker causal wording unless the supplied evidence directly supports causality."
        in markdown
    )


def test_markdown_report_preserves_support_boundary_and_quality_gate() -> None:
    """Generated prose avoids overclaiming and placeholder artifacts."""
    markdown = _ai_research_markdown()

    assert (
        "- Audit boundary: supplied-evidence support only; no outside-world assessment." in markdown
    )
    assert "- External source lookup: not used." in markdown
    assert "Candidate ranking scores inspect deterministic matching only" in markdown
    assert "Support score:" not in markdown
    assert "None" not in markdown
    assert re.search(r"\bnan\b", markdown.lower()) is None
    assert "Phase 5 rule-assessment slice" not in markdown
    assert "Initial Phase 5 rules" not in markdown
    _assert_no_forbidden_capability_language(markdown)


def test_json_report_round_trips_to_audit_report_without_null_values() -> None:
    """JSON output remains tied to the typed report contract."""
    rendered = render_json_report(_ai_research_report())
    parsed = AuditReport.model_validate(json.loads(rendered))

    assert '"document_id": "ai-research-note"' in rendered
    assert "null" not in rendered
    assert parsed.summary.total_claims == 4
    assert parsed.claims[0].claim.id.startswith("claim-")


@pytest.mark.parametrize(
    ("_document_id", "draft_path", "evidence_path", "markdown_path", "json_path"),
    REPORT_FIXTURES,
    ids=[fixture[0] for fixture in REPORT_FIXTURES],
)
def test_checked_in_slice_fixtures_match_current_renderer_output(
    _document_id: str,
    draft_path: Path,
    evidence_path: Path,
    markdown_path: Path,
    json_path: Path,
) -> None:
    """Committed example slices stay synchronized with renderer output."""
    report = _audit_report(draft_path, evidence_path)

    assert markdown_path.read_text(encoding="utf-8") == render_markdown_report(report)
    assert json_path.read_text(encoding="utf-8") == render_json_report(report)


def test_product_readme_report_surfaces_second_family_output_behavior() -> None:
    """The second family report exposes labels and flags without retesting extraction."""
    report = _audit_report(
        EXAMPLES_ROOT / "drafts" / "product-readme-note.md",
        EXAMPLES_ROOT / "evidence" / "product-readme-evidence.yml",
    )
    markdown = render_markdown_report(report)

    assert report.document_id == "product-readme-note"
    assert report.summary.total_claims == 4
    assert report.summary.supported_claims == 2
    assert report.summary.overstated_claims == 2
    assert report.summary.high_risk_claims == 2
    assert "Type: `capability`" in markdown
    assert "Type: `comparative`" in markdown
    assert "Type: `prediction`" in markdown
    assert "Type: `scope`" in markdown
    assert "`future_certainty`" in markdown
    assert "`overconfident_wording`" in markdown
    assert "`scope_overreach`" in markdown
    assert "`source-product-002` | `excerpt-product-003`" in markdown


def test_public_example_files_avoid_private_data_and_secret_markers() -> None:
    """Public draft, evidence, and report files stay fictional or sanitized."""
    public_files = [
        path for directory in PUBLIC_EXAMPLE_DIRS for path in directory.rglob("*") if path.is_file()
    ]

    assert public_files
    for path in public_files:
        text = path.read_text(encoding="utf-8")
        for pattern in PUBLIC_DATA_SENSITIVE_PATTERNS:
            assert re.search(pattern, text, flags=re.IGNORECASE) is None, (
                f"{path.relative_to(PROJECT_ROOT)} matched sensitive-data pattern {pattern!r}"
            )


def test_markdown_report_handles_empty_warning_report_without_empty_sections() -> None:
    """A zero-claim report still renders useful sections and warnings."""
    report = AuditReport(
        document_id="empty-note",
        summary=AuditSummary(total_claims=0),
        evidence_bundle_warnings=["No evidence sources were supplied."],
        limitations=["Supplied evidence only."],
    )
    markdown = render_markdown_report(report)

    assert "## Evidence bundle warnings" in markdown
    assert "No claims were extracted from the draft." in markdown
    assert "No candidate evidence links were found." in markdown
    assert "No rewrite guidance was generated for this report." in markdown
    _assert_no_forbidden_capability_language(markdown)


def test_markdown_report_handles_optional_candidate_and_explanation_fields() -> None:
    """Missing optional candidate fields render as reviewer-friendly text."""
    claim = Claim(id="claim-manual-001", text="The tool reduces review time.", claim_type="causal")
    report = AuditReport(
        document_id="manual-note",
        summary=AuditSummary(total_claims=1, supported_claims=1),
        claims=[
            ClaimAssessment(
                claim=claim,
                support_label="supported",
                risk_label="low",
                candidate_evidence=[
                    EvidenceCandidate(
                        source_id="source-manual",
                        excerpt_id="excerpt-manual",
                        score=0.42,
                    )
                ],
            )
        ],
    )
    markdown = render_markdown_report(report)

    assert "No additional explanation recorded." in markdown
    assert "No rule issue recorded." in markdown
    assert "not dated" in markdown
    assert "not supplied" in markdown
    assert "No rationale recorded." in markdown


def test_markdown_report_includes_explicit_stable_anchors() -> None:
    """Markdown output uses explicit stable anchors for traceability surfaces."""
    report = AuditReport(
        document_id="Manual Note/One",
        summary=AuditSummary(total_claims=1, unsupported_claims=1),
        claims=[
            ClaimAssessment(
                claim=Claim(
                    id="claim-Manual_001",
                    text="The tool reduces every review queue.",
                    claim_type="scope",
                ),
                support_label="unsupported",
                risk_label="high",
                candidate_evidence=[
                    EvidenceCandidate(
                        source_id="Source Manual",
                        excerpt_id="Excerpt_One",
                        score=0.56,
                        source_reliability="medium",
                    )
                ],
                rule_flags=[
                    RuleFlag(
                        id="flag:Mixed/One",
                        claim_id="claim-Manual_001",
                        code="scope_overreach",
                        message="Scope is broader than the supplied evidence.",
                        risk="high",
                    )
                ],
            )
        ],
    )
    markdown = render_markdown_report(report)

    assert '<a id="report-manual-note-one"></a>' in markdown
    assert '<a id="claim-claim-manual-001"></a>' in markdown
    assert '<a id="rule-flag-mixed-one"></a>' in markdown
    assert '<a id="evidence-source-manual-excerpt-one"></a>' in markdown


def test_markdown_report_anchor_ids_are_deterministic_across_renders() -> None:
    """Stable input IDs produce identical Markdown anchor output across renders."""
    report = _ai_research_report()

    assert render_markdown_report(report) == render_markdown_report(report)


def test_markdown_report_surfaces_rule_flag_ids() -> None:
    """Rule flag IDs appear in human-review Markdown alongside rule codes."""
    markdown = _ai_research_markdown()

    assert re.search(
        r'<a id="rule-flag-[a-z0-9-]+"></a> `flag-[a-z0-9-]+` / `overconfident_wording`',
        markdown,
    )


def test_markdown_report_support_quality_notes_appear_only_when_useful() -> None:
    """Support-quality notes surface candidate caveats without adding filler."""
    report = AuditReport(
        document_id="support-quality-note",
        summary=AuditSummary(total_claims=2, supported_claims=1, unsupported_claims=1),
        claims=[
            ClaimAssessment(
                claim=Claim(
                    id="claim-quality",
                    text="The metric covers every queue.",
                    claim_type="scope",
                ),
                support_label="unsupported",
                risk_label="medium",
                candidate_evidence=[
                    EvidenceCandidate(
                        source_id="source-quality-low",
                        excerpt_id="excerpt-quality-low",
                        score=0.44,
                        source_reliability="low",
                        source_date=Date(2024, 1, 1),
                    ),
                    EvidenceCandidate(
                        source_id="source-quality-high",
                        excerpt_id="excerpt-quality-high",
                        score=0.31,
                        source_reliability="high",
                    ),
                ],
                rule_flags=[
                    RuleFlag(
                        id="flag-low-quality",
                        claim_id="claim-quality",
                        code="low_reliability_only",
                        message="Direct support has weak reliability.",
                        risk="medium",
                    ),
                    RuleFlag(
                        id="flag-stale-quality",
                        claim_id="claim-quality",
                        code="stale_source",
                        message="Direct support is stale.",
                        risk="medium",
                    ),
                ],
            ),
            ClaimAssessment(
                claim=Claim(
                    id="claim-clean",
                    text="The tool renders reports.",
                    claim_type="capability",
                ),
                support_label="supported",
                risk_label="low",
                candidate_evidence=[
                    EvidenceCandidate(
                        source_id="source-clean",
                        excerpt_id="excerpt-clean",
                        score=0.82,
                        source_reliability="high",
                        source_date=Date(2026, 1, 1),
                    )
                ],
            ),
        ],
    )
    markdown = render_markdown_report(report)

    assert markdown.count("**Support quality notes**") == 1
    assert (
        "Linked candidate evidence includes low or unknown source reliability metadata." in markdown
    )
    assert "Direct support is flagged for weak source reliability." in markdown
    assert "Direct support is flagged as stale under the configured freshness policy." in markdown
    assert "Candidate evidence mixes reliability or date metadata; review the table." in markdown
    assert (
        "Candidate evidence is linked, but direct supplied-evidence support is not recorded."
        in markdown
    )


def test_markdown_report_renders_explicit_and_fallback_rewrite_guidance() -> None:
    """Renderer guidance covers stored rewrites, rule codes, and label fallbacks."""
    rule_flags = [
        RuleFlag(
            id="flag-numeric",
            claim_id="claim-flags",
            code="numeric_mismatch",
            message="The number does not match supplied evidence.",
            risk="high",
        ),
        RuleFlag(
            id="flag-comparison",
            claim_id="claim-flags",
            code="comparison_missing",
            message="Comparison evidence is missing.",
            risk="medium",
        ),
        RuleFlag(
            id="flag-credential",
            claim_id="claim-flags",
            code="credential_missing_source",
            message="Credential source is missing.",
            risk="medium",
        ),
        RuleFlag(
            id="flag-link",
            claim_id="claim-flags",
            code="public_link_missing_source",
            message="Public link source metadata is missing.",
            risk="medium",
        ),
        RuleFlag(
            id="flag-reliability",
            claim_id="claim-flags",
            code="low_reliability_only",
            message="Direct support has weak reliability.",
            risk="medium",
        ),
        RuleFlag(
            id="flag-stale",
            claim_id="claim-flags",
            code="stale_source",
            message="Direct support is stale.",
            risk="medium",
        ),
        RuleFlag(
            id="flag-date",
            claim_id="claim-flags",
            code="date_missing_support",
            message="Date support is missing.",
            risk="medium",
        ),
    ]
    assessments = [
        ClaimAssessment(
            claim=Claim(id="claim-flags", text="The metric was 99 by 2025.", claim_type="numeric"),
            support_label="unsupported",
            risk_label="high",
            rule_flags=rule_flags,
            suggested_rewrite="Use the supported metric only.",
        ),
        ClaimAssessment(
            claim=Claim(id="claim-needed", text="The result needs a source.", claim_type="scope"),
            support_label="needs_source",
            risk_label="medium",
        ),
        ClaimAssessment(
            claim=Claim(
                id="claim-over", text="The result eliminates all risk.", claim_type="scope"
            ),
            support_label="overstated",
            risk_label="high",
        ),
        ClaimAssessment(
            claim=Claim(
                id="claim-partial", text="The result improved outcomes.", claim_type="causal"
            ),
            support_label="partially_supported",
            risk_label="medium",
        ),
        ClaimAssessment(
            claim=Claim(
                id="claim-not-ready",
                text="Background note without enough audit structure.",
                claim_type="interpretive",
            ),
            support_label="not_audit_ready",
            risk_label="medium",
        ),
    ]
    report = AuditReport(
        document_id="rewrite-note",
        summary=AuditSummary(
            total_claims=5,
            partially_supported_claims=1,
            unsupported_claims=1,
            overstated_claims=1,
            needs_source_claims=1,
            not_audit_ready_claims=1,
            high_risk_claims=2,
        ),
        claims=assessments,
        rule_flags=rule_flags,
    )
    markdown = render_markdown_report(report)

    assert "Suggested rewrite: Use the supported metric only." in markdown
    assert "Correct the number or supply evidence with the matching value." in markdown
    assert "Name the comparison evidence or soften the comparative claim." in markdown
    assert "Add a supplied credential source before keeping this credential claim." in markdown
    assert "Add supplied URL metadata before keeping this public-link claim." in markdown
    assert "Caveat the claim because direct support comes from weak source reliability." in markdown
    assert "Use newer supplied evidence or add a freshness caveat." in markdown
    assert "Add matching date evidence or remove the unsupported date detail." in markdown
    assert "Add a supplied source before presenting this claim." in markdown
    assert "Narrow the claim until it matches the supplied evidence." in markdown
    assert "Keep the supported part and caveat the unsupported part." in markdown
    assert "Support: `not_audit_ready`" in markdown
