"""Audit pipeline coordination."""

from __future__ import annotations

from claim_audit_lab.claim_extraction import extract_claims
from claim_audit_lab.evidence_matching import match_claims_to_evidence
from claim_audit_lab.models import (
    AuditConfig,
    AuditReport,
    AuditSummary,
    ClaimAssessment,
    DraftDocument,
    EvidenceBundle,
)
from claim_audit_lab.rules import assess_claim_support

_PHASE_5_LIMITATION = (
    "Generated by Phase 5 rule-assessment slice; initial deterministic rule checks "
    "are enabled, while full report rendering and CLI workflow remain planned."
)
_CANDIDATE_SCORE_LIMITATION = (
    "Candidate scores rank deterministic text and number overlap only; they are not support scores."
)
_SUPPLIED_EVIDENCE_LIMITATION = (
    "This report only audits support from the supplied evidence bundle; it does not "
    "assess the outside world."
)


def audit_document(
    draft: DraftDocument,
    evidence_bundle: EvidenceBundle,
    config: AuditConfig | None = None,
) -> AuditReport:
    """Run the Phase 5 audit pipeline for a draft and supplied evidence bundle."""
    active_config = config or AuditConfig()
    claims = extract_claims(draft)
    candidate_map = match_claims_to_evidence(claims, evidence_bundle, active_config)

    assessments = [
        assess_claim_support(
            claim,
            evidence_bundle,
            candidate_map.get(claim.id, []),
            active_config,
        )
        for claim in claims
    ]
    rule_flags = [flag for assessment in assessments for flag in assessment.rule_flags]

    evidence_bundle_warnings: list[str] = []
    if not evidence_bundle.sources:
        evidence_bundle_warnings.append(
            "No evidence sources were supplied; extracted claims are marked needs_source."
        )

    return AuditReport(
        document_id=draft.id,
        summary=_build_summary(assessments),
        claims=assessments,
        rule_flags=rule_flags,
        evidence_bundle_warnings=evidence_bundle_warnings,
        limitations=[
            _PHASE_5_LIMITATION,
            _CANDIDATE_SCORE_LIMITATION,
            _SUPPLIED_EVIDENCE_LIMITATION,
        ],
    )


def _build_summary(assessments: list[ClaimAssessment]) -> AuditSummary:
    return AuditSummary(
        total_claims=len(assessments),
        supported_claims=sum(assessment.support_label == "supported" for assessment in assessments),
        partially_supported_claims=sum(
            assessment.support_label == "partially_supported" for assessment in assessments
        ),
        unsupported_claims=sum(
            assessment.support_label == "unsupported" for assessment in assessments
        ),
        overstated_claims=sum(
            assessment.support_label == "overstated" for assessment in assessments
        ),
        needs_source_claims=sum(
            assessment.support_label == "needs_source" for assessment in assessments
        ),
        not_audit_ready_claims=sum(
            assessment.support_label == "not_audit_ready" for assessment in assessments
        ),
        high_risk_claims=sum(assessment.risk_label == "high" for assessment in assessments),
    )


__all__ = ["audit_document"]
