"""Audit pipeline coordination."""

from __future__ import annotations

from claim_audit_lab.claim_extraction import extract_claims
from claim_audit_lab.evidence_matching import match_claims_to_evidence
from claim_audit_lab.models import (
    AuditConfig,
    AuditReport,
    AuditSummary,
    Claim,
    ClaimAssessment,
    DraftDocument,
    EvidenceBundle,
    EvidenceCandidate,
    RiskLabel,
    SupportLabel,
)

_PHASE_4A_LIMITATION = (
    "Generated by Phase 4A vertical slice; rule checks are deferred and support "
    "labels are provisional."
)
_CANDIDATE_SCORE_LIMITATION = (
    "Candidate scores rank deterministic text and number overlap only; they are not support scores."
)
_SUPPLIED_EVIDENCE_LIMITATION = (
    "This report only audits support from the supplied evidence bundle; it does not "
    "assess the outside world."
)


def audit_document(
    draft: DraftDocument,
    evidence_bundle: EvidenceBundle,
    config: AuditConfig | None = None,
) -> AuditReport:
    """Run the Phase 4A audit pipeline for a draft and supplied evidence bundle."""
    active_config = config or AuditConfig()
    claims = extract_claims(draft)
    candidate_map = match_claims_to_evidence(claims, evidence_bundle, active_config)

    assessments = [_build_assessment(claim, candidate_map.get(claim.id, [])) for claim in claims]

    evidence_bundle_warnings: list[str] = []
    if not evidence_bundle.sources:
        evidence_bundle_warnings.append(
            "No evidence sources were supplied; extracted claims are marked needs_source."
        )

    return AuditReport(
        document_id=draft.id,
        summary=_build_summary(assessments),
        claims=assessments,
        rule_flags=[],
        evidence_bundle_warnings=evidence_bundle_warnings,
        limitations=[
            _PHASE_4A_LIMITATION,
            _CANDIDATE_SCORE_LIMITATION,
            _SUPPLIED_EVIDENCE_LIMITATION,
        ],
    )


def _build_assessment(
    claim: Claim,
    candidates: list[EvidenceCandidate],
) -> ClaimAssessment:
    support_label: SupportLabel = "not_audit_ready" if candidates else "needs_source"
    risk_label: RiskLabel = "medium"

    if candidates:
        explanation = (
            "Candidate evidence was found, but Phase 4A does not evaluate whether it "
            "supports the claim."
        )
        limitations = [
            "Rule checks are deferred to Phase 5.",
            "Candidate scores are ranking signals only.",
        ]
    else:
        explanation = "No candidate evidence was found in the supplied bundle."
        limitations = [
            "Rule checks are deferred to Phase 5.",
            "No candidate evidence link is available for this claim.",
        ]

    return ClaimAssessment(
        claim=claim,
        support_label=support_label,
        risk_label=risk_label,
        candidate_evidence=candidates,
        rule_flags=[],
        explanation=explanation,
        limitations=limitations,
    )


def _build_summary(assessments: list[ClaimAssessment]) -> AuditSummary:
    return AuditSummary(
        total_claims=len(assessments),
        needs_source_claims=sum(
            assessment.support_label == "needs_source" for assessment in assessments
        ),
        not_audit_ready_claims=sum(
            assessment.support_label == "not_audit_ready" for assessment in assessments
        ),
        high_risk_claims=sum(assessment.risk_label == "high" for assessment in assessments),
    )


__all__ = ["audit_document"]
