"""Markdown and JSON report rendering."""

from __future__ import annotations

import re

from claim_audit_lab.models import AuditReport, ClaimAssessment, EvidenceCandidate, RuleFlag

_REPORT_HEADER = "Generated by Claim Audit Lab using deterministic supplied-evidence rules."


def render_markdown_report(report: AuditReport) -> str:
    """Render a human-review Markdown report from a typed audit report."""
    lines: list[str] = [
        _anchor("report", report.document_id),
        "",
        f"# Claim Audit Lab report: `{_escape_inline(report.document_id)}`",
        "",
        f"*{_REPORT_HEADER}*",
        "",
        "## Metadata",
        "",
        f"- Document ID: `{_escape_inline(report.document_id)}`",
        "- Audit boundary: supplied-evidence support only; no outside-world assessment.",
        "- External source lookup: not used.",
        "- Match scores and support signals are deterministic supplied-evidence measures; "
        "they are not truth probabilities.",
        "",
        "## Executive summary",
        "",
        _summary_sentence(report),
        "",
        f"- Total claims: {report.summary.total_claims}",
        f"- Supported: {report.summary.supported_claims}",
        f"- Partially supported: {report.summary.partially_supported_claims}",
        f"- Unsupported: {report.summary.unsupported_claims}",
        f"- Overstated: {report.summary.overstated_claims}",
        f"- Needs source: {report.summary.needs_source_claims}",
        f"- Not checkable: {report.summary.not_checkable_claims}",
        f"- High-risk claims: {report.summary.high_risk_claims}",
        "",
        "## Limitations",
        "",
    ]

    lines.extend(_bullets(report.limitations))

    if report.evidence_bundle_warnings:
        lines.extend(["", "## Evidence bundle warnings", ""])
        lines.extend(_bullets(report.evidence_bundle_warnings))

    lines.extend(
        [
            "",
            "## Claim register",
            "",
            "| Claim ID | Claim text | Type | Support | Signal | Risk | Strongest evidence | "
            "Main issue |",
            "| --- | --- | --- | --- | --- | --- | --- | --- |",
        ]
    )
    for assessment in report.claims:
        claim = assessment.claim
        lines.append(
            "| "
            f"`{_escape_table(claim.id)}` | "
            f"{_escape_table(claim.text)} | "
            f"{_escape_table(claim.claim_type)} | "
            f"{_escape_table(assessment.support_label)} | "
            f"{_format_signal(assessment)} | "
            f"{_escape_table(assessment.risk_label)} | "
            f"{_escape_table(_strongest_evidence(assessment))} | "
            f"{_escape_table(_main_issue(assessment))} |"
        )

    if not report.claims:
        lines.extend(["", "No claims were extracted from the draft."])

    lines.extend(["", "## Claim details", ""])
    for assessment in report.claims:
        lines.extend(_claim_detail_lines(assessment))

    lines.extend(_evidence_link_lines(report))
    lines.extend(_rewrite_guidance_lines(report))

    return "\n".join(lines).rstrip() + "\n"


def render_json_report(report: AuditReport) -> str:
    """Render a JSON representation of the typed report."""
    return report.model_dump_json(exclude_none=True, indent=2) + "\n"


def _summary_sentence(report: AuditReport) -> str:
    summary = report.summary
    return (
        f"{summary.total_claims} claims extracted. Findings: "
        f"{summary.supported_claims} supported, "
        f"{summary.partially_supported_claims} partially supported, "
        f"{summary.unsupported_claims} unsupported, "
        f"{summary.overstated_claims} overstated, "
        f"{summary.needs_source_claims} needs-source, "
        f"{summary.not_checkable_claims} not-checkable. "
        f"High-risk claims: {summary.high_risk_claims}."
    )


def _claim_detail_lines(assessment: ClaimAssessment) -> list[str]:
    claim = assessment.claim
    lines = [
        _anchor("claim", claim.id),
        "",
        f"### `{_escape_inline(claim.id)}` ({_escape_text(assessment.support_label)})",
        "",
        f"> {_escape_text(claim.text)}",
        "",
        f"- Type: `{_escape_inline(claim.claim_type)}`",
        f"- Support: `{_escape_inline(assessment.support_label)}`",
        f"- Deterministic support signal: {_format_signal(assessment)}",
        f"- Risk: `{_escape_inline(assessment.risk_label)}`",
        f"- Location: {_escape_text(claim.location or 'not recorded')}",
        "",
        "**Linked support evidence**",
        "",
    ]

    if assessment.candidate_evidence:
        lines.extend(_candidate_table_lines(assessment.candidate_evidence))
    else:
        lines.append("No support evidence met the admission threshold.")

    lines.extend(["", "**Linked counterevidence**", ""])
    if assessment.counterevidence:
        lines.extend(_candidate_table_lines(assessment.counterevidence))
    else:
        lines.append("No counterevidence was linked to this claim.")

    lines.extend(["", "**Rule flags**", ""])
    if assessment.rule_flags:
        lines.extend(_rule_flag_lines(assessment.rule_flags))
    else:
        lines.append("No rule flags.")

    support_quality_notes = _support_quality_notes(assessment)
    if support_quality_notes:
        lines.extend(["", "**Support quality notes**", ""])
        lines.extend(_bullets(support_quality_notes))

    lines.extend(["", "**Explanation**", ""])
    if assessment.explanation:
        lines.append(_escape_text(assessment.explanation))
    else:
        lines.append("No additional explanation recorded.")

    guidance = assessment.rewrite_guidance
    if guidance:
        lines.extend(["", "**Rewrite guidance**", ""])
        lines.extend(_bullets(guidance))

    if assessment.limitations:
        lines.extend(["", "**Claim limitations**", ""])
        lines.extend(_bullets(assessment.limitations))

    lines.append("")
    return lines


def _candidate_table_lines(candidates: list[EvidenceCandidate]) -> list[str]:
    lines = [
        "| Source | Excerpt | Match score | Reliability | Date | URL | Rationale |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]
    for candidate in candidates:
        date = candidate.source_date.isoformat() if candidate.source_date else "not dated"
        url = candidate.source_url or "not supplied"
        rationale = candidate.rationale or "No rationale recorded."
        lines.append(
            "| "
            f"`{_escape_table(candidate.source_id)}` | "
            f"`{_escape_table(candidate.excerpt_id)}` | "
            f"{candidate.score:.4f} | "
            f"{_escape_table(candidate.source_reliability)} | "
            f"{_escape_table(date)} | "
            f"{_escape_table(url)} | "
            f"{_escape_table(rationale)} |"
        )
    return lines


def _rule_flag_lines(flags: list[RuleFlag]) -> list[str]:
    return [
        f"- {_anchor('rule', flag.id)} `{_escape_inline(flag.id)}` / "
        f"`{_escape_inline(flag.code)}` ({flag.risk} risk): {_escape_text(flag.message)}"
        for flag in flags
    ]


def _evidence_link_lines(report: AuditReport) -> list[str]:
    rows: dict[tuple[str, str, str], tuple[EvidenceCandidate, list[str]]] = {}
    for assessment in report.claims:
        for role, candidates in (
            ("support", assessment.candidate_evidence),
            ("counterevidence", assessment.counterevidence),
        ):
            for candidate in candidates:
                key = (candidate.source_id, candidate.excerpt_id, role)
                if key not in rows:
                    rows[key] = (candidate, [])
                elif candidate.score > rows[key][0].score:
                    rows[key] = (candidate, rows[key][1])
                rows[key][1].append(assessment.claim.id)

    lines = [
        "",
        "## Evidence links",
        "",
        "Evidence links come from claim-scoped matches already present in the structured audit "
        "report. Counterevidence is never eligible as support.",
        "",
    ]
    if not rows:
        lines.append("No evidence links were found.")
        return lines

    lines.extend(
        [
            "| Source | Excerpt | Role | Referenced by claims | Best match score | "
            "Reliability | Date | URL |",
            "| --- | --- | --- | --- | --- | --- | --- | --- |",
        ]
    )
    for (source_id, excerpt_id, role), (candidate, claim_ids) in sorted(rows.items()):
        date = candidate.source_date.isoformat() if candidate.source_date else "not dated"
        url = candidate.source_url or "not supplied"
        lines.append(
            "| "
            f"{_anchor('evidence', source_id, excerpt_id)} `{_escape_table(source_id)}` | "
            f"`{_escape_table(excerpt_id)}` | "
            f"{_escape_table(role)} | "
            f"{_escape_table(', '.join(f'`{claim_id}`' for claim_id in claim_ids))} | "
            f"{candidate.score:.4f} | "
            f"{_escape_table(candidate.source_reliability)} | "
            f"{_escape_table(date)} | "
            f"{_escape_table(url)} |"
        )
    return lines


def _rewrite_guidance_lines(report: AuditReport) -> list[str]:
    guidance_by_claim = {
        assessment.claim.id: assessment.rewrite_guidance
        for assessment in report.claims
        if assessment.rewrite_guidance
    }
    lines = ["", "## Rewrite guidance", ""]
    if not guidance_by_claim:
        lines.append("No rewrite guidance was generated for this report.")
        return lines

    for claim_id, guidance in guidance_by_claim.items():
        lines.append(f"### `{_escape_inline(claim_id)}`")
        lines.append("")
        lines.extend(_bullets(guidance))
        lines.append("")
    return lines


def _support_quality_notes(assessment: ClaimAssessment) -> list[str]:
    notes: list[str] = []
    candidates = assessment.candidate_evidence
    reliabilities = {candidate.source_reliability for candidate in candidates}
    codes = {flag.code for flag in assessment.rule_flags}

    if candidates and reliabilities.intersection({"low", "unknown"}):
        notes.append(
            "Linked candidate evidence includes low or unknown source reliability metadata."
        )
    if "low_reliability_only" in codes:
        notes.append("Direct support is flagged for weak source reliability.")
    if "stale_source" in codes:
        notes.append("Direct support is flagged as stale under the configured freshness policy.")
    if len(reliabilities) > 1 or _has_mixed_date_metadata(candidates):
        notes.append("Candidate evidence mixes reliability or date metadata; review the table.")
    if candidates and assessment.support_label in {
        "unsupported",
        "needs_source",
        "not_checkable",
    }:
        notes.append(
            "Candidate evidence is linked, but direct supplied-evidence support is not recorded."
        )

    return _unique(notes)


def _has_mixed_date_metadata(candidates: list[EvidenceCandidate]) -> bool:
    if len(candidates) < 2:
        return False
    return len({candidate.source_date for candidate in candidates}) > 1


def _strongest_evidence(assessment: ClaimAssessment) -> str:
    if not assessment.candidate_evidence:
        return "none linked"
    candidate = assessment.candidate_evidence[0]
    return f"{candidate.source_id} / {candidate.excerpt_id}"


def _main_issue(assessment: ClaimAssessment) -> str:
    if assessment.rule_flags:
        return "; ".join(flag.message for flag in assessment.rule_flags)
    if assessment.explanation:
        return assessment.explanation
    return "No rule issue recorded."


def _format_signal(assessment: ClaimAssessment) -> str:
    if assessment.support_signal is None:
        return "not calculated"
    return f"{assessment.support_signal:.4f}"


def _bullets(items: list[str]) -> list[str]:
    return [f"- {_escape_text(item)}" for item in items]


def _anchor(prefix: str, *parts: str) -> str:
    anchor_id = _anchor_id(prefix, *parts)
    return f'<a id="{anchor_id}"></a>'


def _anchor_id(prefix: str, *parts: str) -> str:
    raw = "-".join((prefix, *parts))
    slug = re.sub(r"[^a-z0-9-]+", "-", raw.lower())
    slug = re.sub(r"-+", "-", slug).strip("-")
    return slug or prefix


def _escape_table(value: str) -> str:
    return _escape_text(value).replace("|", "\\|")


def _escape_inline(value: str) -> str:
    return value.replace("`", "\\`")


def _escape_text(value: str) -> str:
    return value.replace("\n", " ").strip()


def _unique(items: list[str]) -> list[str]:
    unique_items: list[str] = []
    for item in items:
        if item not in unique_items:
            unique_items.append(item)
    return unique_items


__all__ = ["render_json_report", "render_markdown_report"]
