"""Markdown and JSON report rendering."""

from __future__ import annotations

from claim_audit_lab.models import AuditReport, ClaimAssessment, EvidenceCandidate, RuleFlag

_REPORT_HEADER = (
    "Generated by Claim Audit Lab - deterministic rule checks, Phase 6 audit "
    "orchestration, and Phase 7 report rendering enabled; Phase 8 CLI workflow is available."
)


def render_markdown_report(report: AuditReport) -> str:
    """Render a human-review Markdown report from a typed audit report."""
    lines: list[str] = [
        f"# Claim Audit Lab report: `{_escape_inline(report.document_id)}`",
        "",
        f"*{_REPORT_HEADER}*",
        "",
        "## Metadata",
        "",
        f"- Document ID: `{_escape_inline(report.document_id)}`",
        "- Audit boundary: supplied-evidence support only; no outside-world assessment.",
        "- External source lookup: not used.",
        "- Candidate ranking scores inspect deterministic matching only; "
        "they are not support labels.",
        "",
        "## Executive summary",
        "",
        _summary_sentence(report),
        "",
        f"- Total claims: {report.summary.total_claims}",
        f"- Supported: {report.summary.supported_claims}",
        f"- Partially supported: {report.summary.partially_supported_claims}",
        f"- Unsupported: {report.summary.unsupported_claims}",
        f"- Overstated: {report.summary.overstated_claims}",
        f"- Needs source: {report.summary.needs_source_claims}",
        f"- Not audit ready: {report.summary.not_audit_ready_claims}",
        f"- High-risk claims: {report.summary.high_risk_claims}",
        "",
        "## Limitations",
        "",
    ]

    lines.extend(_bullets(report.limitations))

    if report.evidence_bundle_warnings:
        lines.extend(["", "## Evidence bundle warnings", ""])
        lines.extend(_bullets(report.evidence_bundle_warnings))

    lines.extend(
        [
            "",
            "## Claim register",
            "",
            "| Claim ID | Claim text | Type | Support | Risk | Strongest evidence | Main issue |",
            "| --- | --- | --- | --- | --- | --- | --- |",
        ]
    )
    for assessment in report.claims:
        claim = assessment.claim
        lines.append(
            "| "
            f"`{_escape_table(claim.id)}` | "
            f"{_escape_table(claim.text)} | "
            f"{_escape_table(claim.claim_type)} | "
            f"{_escape_table(assessment.support_label)} | "
            f"{_escape_table(assessment.risk_label)} | "
            f"{_escape_table(_strongest_evidence(assessment))} | "
            f"{_escape_table(_main_issue(assessment))} |"
        )

    if not report.claims:
        lines.extend(["", "No claims were extracted from the draft."])

    lines.extend(["", "## Claim details", ""])
    for assessment in report.claims:
        lines.extend(_claim_detail_lines(assessment))

    lines.extend(_evidence_link_lines(report))
    lines.extend(_suggested_rewrite_lines(report))

    return "\n".join(lines).rstrip() + "\n"


def render_json_report(report: AuditReport) -> str:
    """Render a JSON representation of the typed report."""
    return report.model_dump_json(exclude_none=True, indent=2) + "\n"


def _summary_sentence(report: AuditReport) -> str:
    summary = report.summary
    return (
        f"{summary.total_claims} claims extracted. Findings: "
        f"{summary.supported_claims} supported, "
        f"{summary.partially_supported_claims} partially supported, "
        f"{summary.unsupported_claims} unsupported, "
        f"{summary.overstated_claims} overstated, "
        f"{summary.needs_source_claims} needs-source, "
        f"{summary.not_audit_ready_claims} not-audit-ready. "
        f"High-risk claims: {summary.high_risk_claims}."
    )


def _claim_detail_lines(assessment: ClaimAssessment) -> list[str]:
    claim = assessment.claim
    lines = [
        f"### `{_escape_inline(claim.id)}` ({_escape_text(assessment.support_label)})",
        "",
        f"> {_escape_text(claim.text)}",
        "",
        f"- Type: `{_escape_inline(claim.claim_type)}`",
        f"- Support: `{_escape_inline(assessment.support_label)}`",
        f"- Risk: `{_escape_inline(assessment.risk_label)}`",
        f"- Location: {_escape_text(claim.location or 'not recorded')}",
        "",
        "**Candidate evidence**",
        "",
    ]

    if assessment.candidate_evidence:
        lines.extend(_candidate_table_lines(assessment.candidate_evidence))
    else:
        lines.append("No candidate evidence linked from the supplied bundle.")

    lines.extend(["", "**Rule flags**", ""])
    if assessment.rule_flags:
        lines.extend(_rule_flag_lines(assessment.rule_flags))
    else:
        lines.append("No rule flags.")

    lines.extend(["", "**Explanation**", ""])
    if assessment.explanation:
        lines.append(_escape_text(assessment.explanation))
    else:
        lines.append("No additional explanation recorded.")

    guidance = _rewrite_guidance(assessment)
    if guidance:
        lines.extend(["", "**Rewrite guidance**", ""])
        lines.extend(_bullets(guidance))

    if assessment.limitations:
        lines.extend(["", "**Claim limitations**", ""])
        lines.extend(_bullets(assessment.limitations))

    lines.append("")
    return lines


def _candidate_table_lines(candidates: list[EvidenceCandidate]) -> list[str]:
    lines = [
        "| Source | Excerpt | Ranking score | Reliability | Date | URL | Rationale |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]
    for candidate in candidates:
        date = candidate.source_date.isoformat() if candidate.source_date else "not dated"
        url = candidate.source_url or "not supplied"
        rationale = candidate.rationale or "No rationale recorded."
        lines.append(
            "| "
            f"`{_escape_table(candidate.source_id)}` | "
            f"`{_escape_table(candidate.excerpt_id)}` | "
            f"{candidate.score:.4f} | "
            f"{_escape_table(candidate.source_reliability)} | "
            f"{_escape_table(date)} | "
            f"{_escape_table(url)} | "
            f"{_escape_table(rationale)} |"
        )
    return lines


def _rule_flag_lines(flags: list[RuleFlag]) -> list[str]:
    return [
        f"- `{_escape_inline(flag.code)}` ({flag.risk} risk): {_escape_text(flag.message)}"
        for flag in flags
    ]


def _evidence_link_lines(report: AuditReport) -> list[str]:
    rows: dict[tuple[str, str], tuple[EvidenceCandidate, list[str]]] = {}
    for assessment in report.claims:
        for candidate in assessment.candidate_evidence:
            key = (candidate.source_id, candidate.excerpt_id)
            if key not in rows:
                rows[key] = (candidate, [])
            elif candidate.score > rows[key][0].score:
                rows[key] = (candidate, rows[key][1])
            rows[key][1].append(assessment.claim.id)

    lines = [
        "",
        "## Evidence links",
        "",
        "Evidence links come from candidate matches already present in the structured audit "
        "report. They do not add sources beyond the supplied bundle.",
        "",
    ]
    if not rows:
        lines.append("No candidate evidence links were found.")
        return lines

    lines.extend(
        [
            "| Source | Excerpt | Referenced by claims | Best ranking score | "
            "Reliability | Date | URL |",
            "| --- | --- | --- | --- | --- | --- | --- |",
        ]
    )
    for (source_id, excerpt_id), (candidate, claim_ids) in sorted(rows.items()):
        date = candidate.source_date.isoformat() if candidate.source_date else "not dated"
        url = candidate.source_url or "not supplied"
        lines.append(
            "| "
            f"`{_escape_table(source_id)}` | "
            f"`{_escape_table(excerpt_id)}` | "
            f"{_escape_table(', '.join(f'`{claim_id}`' for claim_id in claim_ids))} | "
            f"{candidate.score:.4f} | "
            f"{_escape_table(candidate.source_reliability)} | "
            f"{_escape_table(date)} | "
            f"{_escape_table(url)} |"
        )
    return lines


def _suggested_rewrite_lines(report: AuditReport) -> list[str]:
    guidance_by_claim = {
        assessment.claim.id: guidance
        for assessment in report.claims
        if (guidance := _rewrite_guidance(assessment))
    }
    lines = ["", "## Suggested rewrite guidance", ""]
    if not guidance_by_claim:
        lines.append("No rewrite guidance was generated for this report.")
        return lines

    for claim_id, guidance in guidance_by_claim.items():
        lines.append(f"### `{_escape_inline(claim_id)}`")
        lines.append("")
        lines.extend(_bullets(guidance))
        lines.append("")
    return lines


def _rewrite_guidance(assessment: ClaimAssessment) -> list[str]:
    guidance: list[str] = []
    if assessment.suggested_rewrite:
        guidance.append(f"Suggested rewrite: {assessment.suggested_rewrite}")

    codes = {flag.code for flag in assessment.rule_flags}
    if "numeric_mismatch" in codes:
        guidance.append("Correct the number or supply evidence with the matching value.")
    if "causal_overreach" in codes:
        guidance.append(
            "Use weaker causal wording unless the supplied evidence directly supports causality."
        )
    if "comparison_missing" in codes:
        guidance.append("Name the comparison evidence or soften the comparative claim.")
    if "credential_missing_source" in codes:
        guidance.append("Add a supplied credential source before keeping this credential claim.")
    if "public_link_missing_source" in codes:
        guidance.append("Add supplied URL metadata before keeping this public-link claim.")
    if "overconfident_wording" in codes:
        guidance.append("Replace absolute wording with bounded supplied-evidence language.")
    if "future_certainty" in codes:
        guidance.append(
            "Avoid universal future wording; state only what the supplied evidence covers."
        )
    if "scope_overreach" in codes:
        guidance.append("Narrow the scope to the observed source, fixture, sample, or setting.")
    if "low_reliability_only" in codes:
        guidance.append(
            "Caveat the claim because direct support comes from weak source reliability."
        )
    if "stale_source" in codes:
        guidance.append("Use newer supplied evidence or add a freshness caveat.")
    if "date_missing_support" in codes:
        guidance.append("Add matching date evidence or remove the unsupported date detail.")

    if assessment.support_label == "unsupported" and not guidance:
        guidance.append("Remove the claim or add supplied evidence that directly supports it.")
    if assessment.support_label == "needs_source" and not guidance:
        guidance.append("Add a supplied source before presenting this claim.")
    if assessment.support_label == "overstated" and not guidance:
        guidance.append("Narrow the claim until it matches the supplied evidence.")
    if assessment.support_label == "partially_supported" and not guidance:
        guidance.append("Keep the supported part and caveat the unsupported part.")

    return _unique(guidance)


def _strongest_evidence(assessment: ClaimAssessment) -> str:
    if not assessment.candidate_evidence:
        return "none linked"
    candidate = assessment.candidate_evidence[0]
    return f"{candidate.source_id} / {candidate.excerpt_id}"


def _main_issue(assessment: ClaimAssessment) -> str:
    if assessment.rule_flags:
        return "; ".join(flag.message for flag in assessment.rule_flags)
    if assessment.explanation:
        return assessment.explanation
    return "No rule issue recorded."


def _bullets(items: list[str]) -> list[str]:
    return [f"- {_escape_text(item)}" for item in items]


def _escape_table(value: str) -> str:
    return _escape_text(value).replace("|", "\\|")


def _escape_inline(value: str) -> str:
    return value.replace("`", "\\`")


def _escape_text(value: str) -> str:
    return value.replace("\n", " ").strip()


def _unique(items: list[str]) -> list[str]:
    unique_items: list[str] = []
    for item in items:
        if item not in unique_items:
            unique_items.append(item)
    return unique_items


__all__ = ["render_json_report", "render_markdown_report"]
