"""Markdown and JSON report rendering."""

from __future__ import annotations

from claim_audit_lab.models import AuditReport

_PHASE_5_HEADER = (
    "Generated by Phase 5 rule-assessment slice - deterministic rule checks enabled; "
    "full report rendering and CLI workflow remain planned."
)


def render_markdown_report(report: AuditReport) -> str:
    """Render a minimal Phase 5 Markdown report."""
    lines: list[str] = [
        "# Claim Audit Lab slice report",
        "",
        f"*{_PHASE_5_HEADER}*",
        "",
        "## Summary",
        "",
        f"- Document ID: `{_escape_inline(report.document_id)}`",
        f"- Total claims: {report.summary.total_claims}",
        f"- Supported: {report.summary.supported_claims}",
        f"- Partially supported: {report.summary.partially_supported_claims}",
        f"- Unsupported: {report.summary.unsupported_claims}",
        f"- Overstated: {report.summary.overstated_claims}",
        f"- Needs source: {report.summary.needs_source_claims}",
        f"- Not audit ready: {report.summary.not_audit_ready_claims}",
        f"- High risk: {report.summary.high_risk_claims}",
        "",
        "## Limitations",
        "",
    ]

    lines.extend(_bullets(report.limitations))

    if report.evidence_bundle_warnings:
        lines.extend(["", "## Evidence bundle warnings", ""])
        lines.extend(_bullets(report.evidence_bundle_warnings))

    lines.extend(
        [
            "",
            "## Claim register",
            "",
            "| Claim ID | Type | Label | Risk | Rule flags | Location |",
            "| --- | --- | --- | --- | --- | --- |",
        ]
    )
    for assessment in report.claims:
        claim = assessment.claim
        flag_codes = ", ".join(flag.code for flag in assessment.rule_flags) or "none"
        lines.append(
            "| "
            f"`{_escape_table(claim.id)}` | "
            f"{_escape_table(claim.claim_type)} | "
            f"{_escape_table(assessment.support_label)} | "
            f"{_escape_table(assessment.risk_label)} | "
            f"{_escape_table(flag_codes)} | "
            f"{_escape_table(claim.location or 'not recorded')} |"
        )

    lines.extend(["", "## Candidate evidence", ""])
    for assessment in report.claims:
        claim = assessment.claim
        lines.extend(
            [
                f"### `{_escape_inline(claim.id)}`",
                "",
                f"Claim: {_escape_text(claim.text)}",
                "",
                f"Support label: `{assessment.support_label}`",
                "",
            ]
        )
        if assessment.explanation:
            lines.extend(["Explanation:", "", f"- {_escape_text(assessment.explanation)}", ""])

        if assessment.candidate_evidence:
            lines.append("Candidates:")
            lines.append("")
            for candidate in assessment.candidate_evidence:
                date = candidate.source_date.isoformat() if candidate.source_date else "not dated"
                rationale = candidate.rationale or "No rationale recorded."
                lines.append(
                    "- "
                    f"`{_escape_inline(candidate.source_id)}` / "
                    f"`{_escape_inline(candidate.excerpt_id)}`; "
                    f"score `{candidate.score:.4f}`; "
                    f"reliability `{candidate.source_reliability}`; "
                    f"date `{date}`; "
                    f"{_escape_text(rationale)}"
                )
        else:
            lines.append("No candidate evidence found.")

        if assessment.rule_flags:
            lines.extend(["", "Rule flags:", ""])
            for flag in assessment.rule_flags:
                lines.append(
                    "- "
                    f"`{_escape_inline(flag.code)}`; "
                    f"risk `{flag.risk}`; "
                    f"{_escape_text(flag.message)}"
                )

        if assessment.limitations:
            lines.extend(["", "Claim limitations:", ""])
            lines.extend(_bullets(assessment.limitations))
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def render_json_report(report: AuditReport) -> str:
    """Render a JSON representation of the typed report."""
    return report.model_dump_json(exclude_none=True, indent=2) + "\n"


def _bullets(items: list[str]) -> list[str]:
    return [f"- {_escape_text(item)}" for item in items]


def _escape_table(value: str) -> str:
    return _escape_text(value).replace("|", "\\|")


def _escape_inline(value: str) -> str:
    return value.replace("`", "\\`")


def _escape_text(value: str) -> str:
    return value.replace("\n", " ").strip()


__all__ = ["render_json_report", "render_markdown_report"]
